variables:
  CI_SCRIPTS_DIR: "./ci"
  PATH_ROOT: "/home/gitlab-runner/environments/giftgrab"
  SCRATCH_DIR: "/home/gitlab-runner/giftgrab-scratch"

before_script:
  - rm -rf $SCRATCH_DIR
  - mkdir $SCRATCH_DIR
  - export PKG_CONFIG_PATH="$PATH_ROOT/opt/ffmpeg/3.0.1/lib/pkgconfig:$PKG_CONFIG_PATH"
  - export LD_LIBRARY_PATH="$PATH_ROOT/opt/ffmpeg/3.0.1/lib:$LD_LIBRARY_PATH"
  - export PATH="$PATH_ROOT/usr/local/bin:$PATH_ROOT/opt:$PATH"
  - export GiftGrab_SOURCE_DIR="$(pwd)/src"
  - export GiftGrab_BUILD_DIR="$SCRATCH_DIR/build/GiftGrab"
  - export INSTALL_DIR="$SCRATCH_DIR/install"

# Linux ##################
gift-linux:
  script:
    - "$CI_SCRIPTS_DIR/build-linux.sh"
  tags:
    - gift-linux

# Real-time recording ####
real-time:
  script:
    - export num_lines=$(v2u | grep --count "no signal detected")
    - export DVI2PCIEDUO_REALTIME=test_realtime.py
    - "$CI_SCRIPTS_DIR/test-real-time.sh"
  tags:
    - gift-surg-storz-stack
  only:
    - 31-i420-colour-space-on-epiphan
    - 31-i420-colour-space-on-epiphan-clean-start
    - 48-i420-frame-support-in-video-targets
    - 48-i420-frame-support-in-video-targets-extend-test-suite-to-i420
    - 43-test-long-duration-recordings
    - 60-videoframe_i420-header-not-protected-by-i420-macro
    - 67-create-user-friendly-tests-activate-storz-ci
    - 67-create-user-friendly-tests
    - 65-restructure-cmake-build-process
    - 66-simplify-file-hierarchy
    - 70-corrupt-memory-when-reusing-target
    - 76-tests-not-working-without-opencv
    - 78-add-ctest-to-ci-scripts
