variables:
  CI_SCRIPTS_DIR: "./ci"
  Qt5Widgets_DIR: "/opt/qt5/5.5/gcc_64/lib/cmake/Qt5Widgets"
  Qt5OpenGL_DIR: "/opt/qt5/5.5/gcc_64/lib/cmake/Qt5OpenGL"

before_script:
  - export SCRATCH_DIR="$(pwd)/../scratch-space"
  - export GiftGrab_SOURCE_DIR="$(pwd)/src"
  - export GiftGrab_BUILD_DIR="$SCRATCH_DIR/build/GiftGrab"
  - export INSTALL_DIR="$SCRATCH_DIR/install"
  - export GiftGrab_DIR="$INSTALL_DIR/include/giftgrab"
  - export NiftyMatch_REPO_DIR="$SCRATCH_DIR/source/NiftyMatch"
  - export NiftyMatch_SOURCE_DIR="$NiftyMatch_REPO_DIR/src"
  - export NiftyMatch_BUILD_DIR="$SCRATCH_DIR/build/NiftyMatch"
  - export NiftyMatch_DIR="$INSTALL_DIR/include/nm"
  - export GpuMosaicing_REPO_DIR="$SCRATCH_DIR/source/gpu-mosaicing"
  - export GpuMosaicing_SOURCE_DIR="$GpuMosaicing_REPO_DIR/src"
  - export GpuMosaicing_BUILD_DIR="$SCRATCH_DIR/build/gpu-mosaicing"

# Linux ##################
gift-linux:
  script:
    - "$CI_SCRIPTS_DIR/build-linux.sh"
    - "$CI_SCRIPTS_DIR/deploy-linux.sh"
  tags:
    - gift-linux

# UZ Leuven OR Workstation 1603 - see GiftGrab#46
or-recording-compatibility:
  script:
    - export PATH=/home/gitlab-runner/environments/giftgrab/usr/local/bin:$PATH
    - export LD_LIBRARY_PATH=/home/gitlab-runner/environments/giftgrab/opt/ffmpeg/3.0.1/lib:$LD_LIBRARY_PATH
    - export EpiphanSDK_DIR=/home/gitlab-runner/environments/giftgrab/opt/include/epiphansdk
    - export FFmpeg_DIR=/home/gitlab-runner/environments/giftgrab/opt/ffmpeg/3.0.1
    - export num_lines=$(v2u | grep --count "no signal detected")
    - export DVI2PCIEDUO_REALTIME=test_realtime.py
    - "$CI_SCRIPTS_DIR/build-uzl1603.sh"
    - "$CI_SCRIPTS_DIR/test-uzl1603.sh"
    - "$CI_SCRIPTS_DIR/build-uzl1603-i420.sh"
    - "$CI_SCRIPTS_DIR/test-uzl1603-i420.sh"
  tags:
    - gift-surg-storz-stack
  only:
    - 31-i420-colour-space-on-epiphan
    - 31-i420-colour-space-on-epiphan-clean-start
    - 48-i420-frame-support-in-video-targets
    - 48-i420-frame-support-in-video-targets-extend-test-suite-to-i420
    - 43-test-long-duration-recordings
    - 60-videoframe_i420-header-not-protected-by-i420-macro
    - 67-create-user-friendly-tests-activate-storz-ci
    - 67-create-user-friendly-tests
    - 65-restructure-cmake-build-process
