variables:
  CI_SCRIPTS_DIR: "./ci"
  SCRATCH_DIR: "/home/gitlab-runner/giftgrab-scratch"
  CTEST_OUTPUT_ON_FAILURE: "1"
  EpiphanSDK_DIR: "/home/gitlab-runner/environments/giftgrab/opt/epiphan_sdk-3.30.3.0007"

before_script:
  - rm -rf $SCRATCH_DIR
  - mkdir $SCRATCH_DIR
  - export GiftGrab_SOURCE_DIR="$(pwd)/src"
  - source "$CI_SCRIPTS_DIR/utils.sh"

stages:
  - install
  - test_cmake
  - test_pypi

################## Platform: CMake ##################
################## Target: All ######################
linux:
  stage: install
  script:
    # prepare environment
    - export GiftGrab_BUILD_DIR="$SCRATCH_DIR/build/GiftGrab-linux"
    - export INSTALL_DIR="$SCRATCH_DIR/install-linux"
    - rm -rf "$GiftGrab_BUILD_DIR"
    - mkdir -p "$GiftGrab_BUILD_DIR"
    - cd "$GiftGrab_BUILD_DIR"
    # start script
    - pwd
    # bare-bones build
    - cmake -D CMAKE_INSTALL_PREFIX="$INSTALL_DIR" "$GiftGrab_SOURCE_DIR"
    - make -j; exit_on_fail
    # no ctest: no features activated to be tested yet
    - make install
    # Python and tests (currently all python)
    - cmake -D BUILD_PYTHON=ON -D BUILD_TESTS=ON .
    - make -j; exit_on_fail
    # no ctest: no features activated to be tested yet
    - make install
    # HEVC support
    - cmake -D USE_HEVC=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # HEVC support with x265
    - cmake -D ENABLE_GPL=ON -D USE_X265=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # turn x265 off explicitly for combination testing
    - cmake -D ENABLE_GPL=OFF -D USE_X265=OFF .
    # hardware-accelerated HEVC
    - cmake -D ENABLE_NONFREE=ON -D USE_NVENC=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # Xvid support (OpenCV should get switched here)
    - cmake -D USE_XVID=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # VP9 support
    - cmake -D USE_VP9=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # build docs
    - cmake -D BUILD_DOC=ON .
    - make -j; exit_on_fail
    # no ctest: only checking whether doc building
    # properly here
    - make install
  tags:
    - gift-linux

################## Platform: PyPI ##################
################## Target: All #####################
pypi:
  stage: install
  script:
    - GiftGrab_PyPI_BUILD_DIR="$SCRATCH_DIR/pypi"
    - GiftGrab_PyPI_INSTALL_DIR="$GiftGrab_PyPI_BUILD_DIR/install"
    - GiftGrab_venv=venv
    - rm -rf "$GiftGrab_PyPI_BUILD_DIR"
    - mkdir "$GiftGrab_PyPI_BUILD_DIR"
    - rm -rf "$GiftGrab_PyPI_INSTALL_DIR"
    - mkdir "$GiftGrab_PyPI_INSTALL_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - export GiftGrab_PyPI_DIST_DIR=dist
    - rm -rfv "$GiftGrab_PyPI_DIST_DIR"
    - cd "$GiftGrab_SOURCE_DIR"
    - python setup.py sdist
    - mv "$GiftGrab_PyPI_DIST_DIR" "$GiftGrab_PyPI_BUILD_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - virtualenv $GiftGrab_venv
    - cd $GiftGrab_venv
    - source bin/activate
    - ls -alh ./*
    - PyPI_INSTALLER="../$GiftGrab_PyPI_DIST_DIR/$(ls ../$GiftGrab_PyPI_DIST_DIR | grep tar.gz)"
    - if [ -z "$PyPI_INSTALLER" ]; then exit 1; fi
    # Python and tests (currently all python)
    - pip install -vvv --upgrade "$PyPI_INSTALLER"
    # HEVC support
    - pip install -vvv --install-option="--hevc" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc-bgra; exit_on_fail
    # HEVC support with x265
    - pip install -vvv --install-option="--hevc" --install-option="--enable-gpl" --install-option="--x265" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc-bgra; exit_on_fail
    - test-giftgrab-hevc-i420; exit_on_fail
    # hardware-accelerated HEVC
    - pip install -vvv --install-option="--hevc" --install-option="--enable-nonfree" --install-option="--nvenc" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc-bgra; exit_on_fail
    - test-giftgrab-hevc-i420; exit_on_fail
    # Xvid support
    - pip install -vvv --install-option="--hevc" --install-option="--enable-nonfree" --install-option="--nvenc" --install-option="--xvid" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-xvid-bgra; exit_on_fail
    # VP9 support
    - pip install -vvv --install-option="--hevc" --install-option="--enable-nonfree" --install-option="--nvenc" --install-option="--xvid" --install-option="--vp9" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-vp9-bgra; exit_on_fail
    - test-giftgrab-vp9-i420; exit_on_fail
    - deactivate
  tags:
    - gift-linux
    - gift-pypi

################## Device: Epiphan DVI2PCIe Duo ##################
################## Platform: PyPI ################################
################## Target: All ###################################
pypi-epiphan-dvi2pcie-duo:
  stage: test_pypi
  script:
    # for custom FFmpeg:
    - export STORZ_STACK_GIFTGRAB_ENV_ROOT=/home/gitlab-runner/environments/giftgrab/usr/local
    # TODO - export PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/bin":$PATH
    - export PKG_CONFIG_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib/pkgconfig":$PKG_CONFIG_PATH
    # for custom libVLC
    - export LIBVLC_INCLUDE_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/include"
    - export LIBVLC_LIBRARY_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib"
    - GiftGrab_PyPI_BUILD_DIR="$SCRATCH_DIR/pypi-epiphan-dvi2pcie-duo"
    - GiftGrab_PyPI_INSTALL_DIR="$GiftGrab_PyPI_BUILD_DIR/install"
    - GiftGrab_venv=venv
    - rm -rf "$GiftGrab_PyPI_BUILD_DIR"
    - mkdir "$GiftGrab_PyPI_BUILD_DIR"
    - rm -rf "$GiftGrab_PyPI_INSTALL_DIR"
    - mkdir "$GiftGrab_PyPI_INSTALL_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - export GiftGrab_PyPI_DIST_DIR=dist
    - rm -rfv "$GiftGrab_PyPI_DIST_DIR"
    - cd "$GiftGrab_SOURCE_DIR"
    - python setup.py sdist
    - mv "$GiftGrab_PyPI_DIST_DIR" "$GiftGrab_PyPI_BUILD_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - virtualenv $GiftGrab_venv
    - cd $GiftGrab_venv
    - source bin/activate
    - ls -alh ./*
    - PyPI_INSTALLER="../$GiftGrab_PyPI_DIST_DIR/$(ls ../$GiftGrab_PyPI_DIST_DIR | grep tar.gz)"
    - if [ -z "$PyPI_INSTALLER" ]; then exit 1; fi
    # because pip seems to be getting confused about install options on Storz stack:
    - pip install PyYAML
    - pip install pytest
    # Epiphan DVI2PCIe Duo support (OpenCV only)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--enable-nonfree" --install-option="--xvid" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --install-option="--no-i420" --upgrade "$PyPI_INSTALLER"
    # Disabled the BGRA tests of Epiphan DVI2PCIe Duo (currently using OpenCV) until issue #115 is resolved
    # - test-giftgrab-epiphan-dvi2pcieduo-bgra; exit_on_fail
    # - edd-dvi-bgra-hevc; exit_on_fail
    # - edd-sdi-bgra-hevc; exit_on_fail
    # - edd-dvi-bgra-xvid; exit_on_fail
    # - edd-sdi-bgra-xvid; exit_on_fail
    # - edd-dvi-bgra-vp9; exit_on_fail
    # - edd-sdi-bgra-vp9; exit_on_fail
    # Epiphan DVI2PCIe Duo support (libVLC only)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--enable-nonfree" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --install-option="--no-bgra" --upgrade "$PyPI_INSTALLER"
    # TODO: issue #102
    # - test-giftgrab-epiphan-dvi2pcieduo-i420; exit_on_fail
    # Disabled the BGRA tests of Epiphan DVI2PCIe Duo (currently using OpenCV) until issue #115 is resolved
    - edd-dvi-i420-hevc; exit_on_fail
    - edd-sdi-i420-hevc; exit_on_fail
    - edd-dvi-i420-vp9; exit_on_fail
    - edd-sdi-i420-vp9; exit_on_fail
    - ls -alh ./*.mp4
    # - ls -alh ./*.avi
    - ls -alh ./*.webm
    - rm -f ./*.mp4 ./*.avi ./*.webm
    # Epiphan DVI2PCIe Duo support (both OpenCV and libVLC)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--enable-nonfree" --install-option="--xvid" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --upgrade "$PyPI_INSTALLER"
    # Disabled the BGRA tests of Epiphan DVI2PCIe Duo (currently using OpenCV) until issue #115 is resolved
    # - test-giftgrab-epiphan-dvi2pcieduo-bgra; exit_on_fail
    # - edd-dvi-bgra-hevc; exit_on_fail
    # - edd-sdi-bgra-hevc; exit_on_fail
    # - edd-dvi-bgra-xvid; exit_on_fail
    # - edd-sdi-bgra-xvid; exit_on_fail
    # - edd-dvi-bgra-vp9; exit_on_fail
    # - edd-sdi-bgra-vp9; exit_on_fail
    - edd-dvi-i420-hevc; exit_on_fail
    - edd-sdi-i420-hevc; exit_on_fail
    - edd-dvi-i420-vp9; exit_on_fail
    - edd-sdi-i420-vp9; exit_on_fail
    - ls -alh ./*.mp4
    # - ls -alh ./*.avi
    - ls -alh ./*.webm
    - rm -f ./*.mp4 ./*.avi ./*.webm
    # Epiphan DVI2PCIe Duo support (both OpenCV and Epiphan SDK)
    # dummy var, to induce width_offset in test_epiphan_py_module.py
    # see definition of width_offset in test_epiphan_py_module.py (Epiphan DVI2PCIe Duo tests)
    - export USE_EPIPHANSDK=3
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--enable-nonfree" --install-option="--xvid" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --install-option="--epiphansdk" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-epiphan-dvi2pcieduo-i420; exit_on_fail
    - edd-dvi-i420-hevc; exit_on_fail
    - edd-sdi-i420-hevc; exit_on_fail
    - edd-dvi-i420-vp9; exit_on_fail
    - edd-sdi-i420-vp9; exit_on_fail
    - ls -alh ./*.mp4
    - ls -alh ./*.webm
    - rm -f ./*.mp4 ./*.avi ./*.webm
    - unset USE_EPIPHANSDK  # remove dummy var
    - deactivate
  tags:
    - gift-linux
    - gift-pypi
    - gift-epiphan-dvi2pcie-duo
  only:
    - 121-standardise-factory-pattern-for-sources

################## Device: Epiphan DVI2PCIe Duo ##################
epiphan-dvi2pcie-duo:
  stage: test_cmake
  script:
    # prepare environment
    - export GiftGrab_BUILD_DIR="$SCRATCH_DIR/build/GiftGrab-epiphan-dvi2pcie-duo"
    - export INSTALL_DIR="$SCRATCH_DIR/install-epiphan-dvi2pcie-duo"
    - rm -rf "$GiftGrab_BUILD_DIR"
    - mkdir -p "$GiftGrab_BUILD_DIR"
    - cd "$GiftGrab_BUILD_DIR"
    # start script
    # for custom FFmpeg:
    - export STORZ_STACK_GIFTGRAB_ENV_ROOT=/home/gitlab-runner/environments/giftgrab/usr/local
    # TODO - export PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/bin":$PATH
    - export PKG_CONFIG_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib/pkgconfig":$PKG_CONFIG_PATH
    # for custom libVLC
    - export LIBVLC_INCLUDE_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/include"
    - export LIBVLC_LIBRARY_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib"
    # test BGRA colour space
    - cmake -D USE_EPIPHAN_DVI2PCIE_DUO=ON -D USE_I420=OFF -D BUILD_PYTHON=ON -D BUILD_TESTS=ON -D USE_HEVC=ON -D USE_NVENC=ON -D ENABLE_NONFREE=ON "$GiftGrab_SOURCE_DIR"
    - make -j; exit_on_fail
    - check_epiphan_alive
    # -E => excluding VideoSourceFactory tests
    - ctest -E Epiphan_DVI2PCIeDuo_VideoSourceFactory; exit_on_fail
    # test I420 colour space
    - cmake -D USE_BGRA=OFF -D USE_I420=ON .
    - make -j; exit_on_fail
    - check_epiphan_alive
    # -E => excluding VideoSourceFactory tests
    - ctest -E Epiphan_DVI2PCIeDuo_VideoSourceFactory; exit_on_fail
    # test VideoSourceFactory (needs both colour spaces enabled)
    - cmake -D USE_BGRA=ON -D USE_I420=ON .
    - make -j; exit_on_fail
    - check_epiphan_alive
    - ctest -R Epiphan_DVI2PCIeDuo_VideoSourceFactory; exit_on_fail
    # Epiphan SDK
    # dummy var, to induce width_offset in test_epiphan_py_module.py
    # see definition of width_offset in test_epiphan_py_module.py (Epiphan DVI2PCIe Duo tests)
    - export USE_EPIPHANSDK=3
    - cmake -D USE_EPIPHANSDK=ON -D ENABLE_NONFREE=ON .
    - make -j; exit_on_fail
    - check_epiphan_alive
    - ctest; exit_on_fail
    - unset USE_EPIPHANSDK  # remove dummy var
  tags:
    - gift-linux
    - gift-epiphan-dvi2pcie-duo
  only:
    - 121-standardise-factory-pattern-for-sources
