variables:
  CI_SCRIPTS_DIR: "./ci"
  SCRATCH_DIR: "/home/gitlab-runner/giftgrab-scratch"

before_script:
  - rm -rf $SCRATCH_DIR
  - mkdir $SCRATCH_DIR
  - export GiftGrab_SOURCE_DIR="$(pwd)/src"
  - export GiftGrab_BUILD_DIR="$SCRATCH_DIR/build/GiftGrab"
  - export INSTALL_DIR="$SCRATCH_DIR/install"
  - source "$CI_SCRIPTS_DIR/utils.sh"
  - rm -rf "$GiftGrab_BUILD_DIR"
  - mkdir -p "$GiftGrab_BUILD_DIR"
  - cd "$GiftGrab_BUILD_DIR"

# Linux ##################
gift-linux:
  script:
    - pwd
    # bare-bones build
    - cmake -D CMAKE_INSTALL_PREFIX="$INSTALL_DIR" "$GiftGrab_SOURCE_DIR"
    - make -j; exit_on_fail
    # no ctest: no features activated to be tested yet
    - make install
    # Python and tests (currently all python)
    - cmake -D BUILD_PYTHON=ON -D BUILD_TESTS=ON .
    - make -j; exit_on_fail
    # no ctest: no features activated to be tested yet
    - make install
    # HEVC support
    - cmake -D USE_HEVC=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # HEVC support with x265
    - cmake -D ENABLE_GPL=ON -D USE_X265=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # turn x265 off explicitly for combination testing
    - cmake -D ENABLE_GPL=OFF -D USE_X265=OFF .
    # hardware-accelerated HEVC
    - cmake -D USE_NVENC=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # Xvid support (OpenCV should get switched here)
    - cmake -D USE_XVID=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # VP9 support
    - cmake -D USE_VP9=ON .
    - make -j; exit_on_fail
    - ctest; exit_on_fail
    - make install
    # Epiphan DVI2PCIe Duo support (OpenCV)
    - cmake -D USE_EPIPHAN_DVI2PCIE_DUO=ON .
    - make -j; exit_on_fail
    # no ctest for Epiphan DVI2PCIe Duo on
    # general-purpose Linux test server
    - make install
    # Epiphan DVI2PCIe Duo support (EpiphanSDK)
    - cmake -D USE_I420=ON .
    - make -j; exit_on_fail
    # no ctest for Epiphan DVI2PCIe Duo on
    # general-purpose Linux test server
    - make install
    # build docs
    - cmake -D BUILD_DOC=ON .
    - make -j; exit_on_fail
    # no ctest: only checking whether doc building
    # properly here
    - make install
  tags:
    - gift-linux

pypi-packaging:
  script:
    - GiftGrab_PyPI_BUILD_DIR="$SCRATCH_DIR/pypi"
    - GiftGrab_PyPI_INSTALL_DIR="$GiftGrab_PyPI_BUILD_DIR/install"
    - GiftGrab_venv=venv
    - rm -rf "$GiftGrab_PyPI_BUILD_DIR"
    - mkdir "$GiftGrab_PyPI_BUILD_DIR"
    - rm -rf "$GiftGrab_PyPI_INSTALL_DIR"
    - mkdir "$GiftGrab_PyPI_INSTALL_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - export GiftGrab_PyPI_DIST_DIR=dist
    - rm -rfv "$GiftGrab_PyPI_DIST_DIR"
    - cd "$GiftGrab_SOURCE_DIR"
    - python setup.py sdist
    - mv "$GiftGrab_PyPI_DIST_DIR" "$GiftGrab_PyPI_BUILD_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - virtualenv $GiftGrab_venv
    - cd $GiftGrab_venv
    - source bin/activate
    - ls -alh ./*
    - PyPI_INSTALLER="../$GiftGrab_PyPI_DIST_DIR/$(ls ../$GiftGrab_PyPI_DIST_DIR | grep tar.gz)"
    - if [ -z "$PyPI_INSTALLER" ]; then exit 1; fi
    # Python and tests (currently all python)
    - pip install -vvv --upgrade "$PyPI_INSTALLER"
    # HEVC support
    - pip install -vvv --install-option="--hevc" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc; exit_on_fail
    # HEVC support with x265
    - pip install -vvv --install-option="--hevc" --install-option="--enable-gpl" --install-option="--x265" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc; exit_on_fail
    # hardware-accelerated HEVC
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc; exit_on_fail
    # Xvid support (OpenCV should get switched here)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--xvid" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-xvid; exit_on_fail
    # VP9 support
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--xvid" --install-option="--vp9" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-vp9; exit_on_fail
    # Epiphan DVI2PCIe Duo support (OpenCV)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--xvid" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --upgrade "$PyPI_INSTALLER"
    # Epiphan DVI2PCIe Duo support (EpiphanSDK)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--xvid" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --install-option="--i420" --upgrade "$PyPI_INSTALLER"
    - deactivate
  tags:
    - gift-linux
    - gift-pypi

pypi-packaging-epiphan:
  script:
    # for custom FFmpeg:
    - export STORZ_STACK_GIFTGRAB_ENV_ROOT=/home/gitlab-runner/environments/giftgrab/usr/local
    - export PKG_CONFIG_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib/pkgconfig":$PKG_CONFIG_PATH
    # for custom libVLC
    - export LIBVLC_INCLUDE_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/include"
    - export LIBVLC_LIBRARY_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib"
    - GiftGrab_PyPI_BUILD_DIR="$SCRATCH_DIR/pypi"
    - GiftGrab_PyPI_INSTALL_DIR="$GiftGrab_PyPI_BUILD_DIR/install"
    - GiftGrab_venv=venv
    - rm -rf "$GiftGrab_PyPI_BUILD_DIR"
    - mkdir "$GiftGrab_PyPI_BUILD_DIR"
    - rm -rf "$GiftGrab_PyPI_INSTALL_DIR"
    - mkdir "$GiftGrab_PyPI_INSTALL_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - export GiftGrab_PyPI_DIST_DIR=dist
    - rm -rfv "$GiftGrab_PyPI_DIST_DIR"
    - cd "$GiftGrab_SOURCE_DIR"
    - python setup.py sdist
    - mv "$GiftGrab_PyPI_DIST_DIR" "$GiftGrab_PyPI_BUILD_DIR"
    - cd "$GiftGrab_PyPI_BUILD_DIR"
    - virtualenv $GiftGrab_venv
    - cd $GiftGrab_venv
    - source bin/activate
    - ls -alh ./*
    - PyPI_INSTALLER="../$GiftGrab_PyPI_DIST_DIR/$(ls ../$GiftGrab_PyPI_DIST_DIR | grep tar.gz)"
    - if [ -z "$PyPI_INSTALLER" ]; then exit 1; fi
    # because pip seems to be getting confused about install options on Storz stack:
    - pip install PyYAML
    - pip install pytest
    # Epiphan DVI2PCIe Duo support (OpenCV)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--xvid" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc; exit_on_fail
    - test-giftgrab-xvid; exit_on_fail
    - test-giftgrab-vp9; exit_on_fail
    - test-giftgrab-epiphan-dvi2pcieduo-bgr24; exit_on_fail
    - edd-dvi-bgr24-hevc; exit_on_fail
    - edd-sdi-bgr24-hevc; exit_on_fail
    - edd-dvi-bgr24-xvid; exit_on_fail
    - edd-sdi-bgr24-xvid; exit_on_fail
    - edd-dvi-bgr24-vp9; exit_on_fail
    - edd-sdi-bgr24-vp9; exit_on_fail
    # Epiphan DVI2PCIe Duo support (EpiphanSDK)
    - pip install -vvv --install-option="--hevc" --install-option="--nvenc" --install-option="--xvid" --install-option="--vp9" --install-option="--epiphan-dvi2pcie-duo" --install-option="--i420" --upgrade "$PyPI_INSTALLER"
    - test-giftgrab-hevc; exit_on_fail
    - test-giftgrab-xvid; exit_on_fail
    - test-giftgrab-vp9; exit_on_fail
    - test-giftgrab-epiphan-dvi2pcieduo-i420; exit_on_fail
    - edd-dvi-i420-hevc; exit_on_fail
    - edd-sdi-i420-hevc; exit_on_fail
    - edd-dvi-i420-vp9; exit_on_fail
    - edd-sdi-i420-vp9; exit_on_fail
    - ls -alh ./*.mp4
    - ls -alh ./*.avi
    - ls -alh ./*.webm
    - rm -f ./*.mp4 ./*.avi ./*.webm
    - deactivate
  tags:
    - gift-pypi
    - gift-surg-storz-stack

# Real-time recording ####
real-time:
  script:
    # for custom FFmpeg:
    - export STORZ_STACK_GIFTGRAB_ENV_ROOT=/home/gitlab-runner/environments/giftgrab/usr/local
    - export PKG_CONFIG_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib/pkgconfig":$PKG_CONFIG_PATH
    # for custom libVLC
    - export LIBVLC_INCLUDE_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/include"
    - export LIBVLC_LIBRARY_PATH="$STORZ_STACK_GIFTGRAB_ENV_ROOT/lib"
    - cmake -D USE_EPIPHAN_DVI2PCIE_DUO=ON -D BUILD_PYTHON=ON -D BUILD_TESTS=ON -D USE_HEVC=ON -D USE_NVENC=ON -D USE_VP9=ON "$GiftGrab_SOURCE_DIR"
    - make -j; exit_on_fail
    # test BGR24 colour space
    - check_epiphan_alive
    - ctest; exit_on_fail
    # test I420 colour space
    - cmake -D USE_I420=ON .
    - make -j; exit_on_fail
    # check smt connected to Epiphan
    - check_epiphan_alive
    - ctest; exit_on_fail
  tags:
    - gift-surg-storz-stack
  only:
    - 31-i420-colour-space-on-epiphan
    - 31-i420-colour-space-on-epiphan-clean-start
    - 48-i420-frame-support-in-video-targets
    - 48-i420-frame-support-in-video-targets-extend-test-suite-to-i420
    - 43-test-long-duration-recordings
    - 60-videoframe_i420-header-not-protected-by-i420-macro
    - 67-create-user-friendly-tests-activate-storz-ci
    - 67-create-user-friendly-tests
    - 65-restructure-cmake-build-process
    - 66-simplify-file-hierarchy
    - 70-corrupt-memory-when-reusing-target
    - 76-tests-not-working-without-opencv
    - 78-add-ctest-to-ci-scripts
    - 77-use_libvlc-still-appearing-in-cmake
    - 68-publish-giftgrab-on-pypi
    - 84-switch-to-bsd-compatible-x265-alternative
    - 83-revive-libvlc-video-source
